DEVICE_ID = 1

CIRCUITPY_WIFI_SSID = ""
CIRCUITPY_WIFI_PASSWORD = ""
INTERNET_CONNECTION_TEST_URL = "http://google.com"
SERVER_CONNECTION_TEST_URL = ""
SERVER_CONNECTION_EXPECTED_RESPONSE = ""
SERVER_POST_URL = ""
